// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJuMXUM062WWvyCQToghOohuvlk85K_e8',
    appId: '1:886127583198:web:5b328660242ff52217c74f',
    messagingSenderId: '886127583198',
    projectId: 'alexrra-app',
    authDomain: 'alexrra-app.firebaseapp.com',
    storageBucket: 'alexrra-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6uV39MXbtxz7EGx-jaqQzY0QeQfc_XTU',
    appId: '1:831826240209:android:10ef03f318ab67b4105bf0',
    messagingSenderId: '831826240209',
    projectId: 'nbbank-f77bb',
    storageBucket: 'nbbank-f77bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwIIHYJ5cfwnpmsV0TkL20ZDvPBTClr5g',
    appId: '1:831826240209:ios:0e9bd1dfb2ecd796105bf0',
    messagingSenderId: '831826240209',
    projectId: 'nbbank-f77bb',
    storageBucket: 'nbbank-f77bb.firebasestorage.app',
    iosBundleId: 'com.nbbankk.adewebdevvv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHc9d-wjDUTPR_y81SHVIi2dMYXTQ-BAI',
    appId: '1:886127583198:ios:01fd45f2d4b12ebc17c74f',
    messagingSenderId: '886127583198',
    projectId: 'alexrra-app',
    storageBucket: 'alexrra-app.firebasestorage.app',
    iosClientId: '886127583198-9j8tmg3d0fe7kgskc7rp9c1rqke8ilmk.apps.googleusercontent.com',
    iosBundleId: 'com.sahlapay.ovopay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJuMXUM062WWvyCQToghOohuvlk85K_e8',
    appId: '1:886127583198:web:46afa9d7d7c3ce0617c74f',
    messagingSenderId: '886127583198',
    projectId: 'alexrra-app',
    authDomain: 'alexrra-app.firebaseapp.com',
    storageBucket: 'alexrra-app.firebasestorage.app',
  );
}